In [114]:
import numpy as np
import random

### 1. Utwórz jednowymiarową tablicę (wektor) z pierwszymi 10 dodatnimi liczbami całkowitymi i wyświetl jej wartość.

In [115]:
a = np.arange(1,11)
print("a =", a)

a = [ 1  2  3  4  5  6  7  8  9 10]


### 2. Utwórz dwuwymiarową tablicę (macierz) o rozmiarze 3x3, wypełnij ją zerami i wyświetl jej wartość.

In [116]:
a = np.zeros((3, 3), dtype="u4")
print("a =\n", a)

a =
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


### 3. Utwórz tablicę o rozmiarze 5x5, wypełnij ją losowymi liczbami całkowitymi z zakresu od 1 do 10 i wyświetl jej wartość.

In [117]:
a = np.random.randint(1, 11, size=(5, 5))
print("a =\n", a)

a =
 [[6 1 5 9 5]
 [3 3 3 7 5]
 [3 3 1 6 6]
 [1 8 7 8 5]
 [9 6 7 5 1]]


### 4. Utwórz tablicę o rozmiarze 4x4, wypełnij ją losowymi liczbami rzeczywistymi z zakresu od 0 do 1 i wyświetl jej wartość.

In [118]:
a = np.random.random((4, 4))
print("a =\n", a)

a =
 [[0.61971847 0.11069952 0.69397551 0.72979924]
 [0.95863162 0.62564938 0.8348982  0.68652677]
 [0.04956995 0.10037866 0.12768888 0.90435335]
 [0.72194026 0.94612791 0.87100442 0.18543937]]


### 5. Utwórz dwie jednowymiarowe tablice o rozmiarze 5, wypełnij je losowymi liczbami całkowitymi z zakresu od 1 do 10 i wykonaj na nich operacje dodawania, odejmowania i mnożenia.

In [119]:
a = np.random.randint(1, 11, size=5)
b = np.random.randint(1, 11, size=5)
print("a =", a)
print("b =", b)
print("a + b =", a+b)
print("a - b =", a-b)
print("b - a =", b-a)
print("a * 5 =", a*5)
print("b * 5 =", b*5)
print("a * b =", a*b)

a = [9 8 2 5 9]
b = [5 7 9 1 5]
a + b = [14 15 11  6 14]
a - b = [ 4  1 -7  4  4]
b - a = [-4 -1  7 -4 -4]
a * 5 = [45 40 10 25 45]
b * 5 = [25 35 45  5 25]
a * b = [45 56 18  5 45]


### 6. Utwórz dwa wektory o rozmiarze 7, wypełnij je losowymi liczbami i znajdź ich iloczyn skalarny.

In [120]:
a = np.random.randint(1, 11, size=7)
b = np.random.randint(1, 11, size=7)
print("a =", a)
print("b =", b)
print("a • b =", np.dot(a,b))

a = [ 7  3  9  9  5 10  9]
b = [2 6 5 8 4 5 4]
a • b = 255


### 7. Utwórz dwie macierze o rozmiarach 2x2 i 2x3, wypełnij je losowymi liczbami całkowitymi z zakresu od 1 do 10 i pomnóż je.

In [121]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 3))
print("a =\n", a)
print("b =\n", b)
print("a • b =\n", np.dot(a, b))

a =
 [[1 7]
 [5 5]]
b =
 [[6 7 2]
 [1 3 7]]
a • b =
 [[13 28 51]
 [35 50 45]]


### 8. Utwórz macierz o rozmiarze 3x3, wypełnij ją losowymi liczbami całkowitymi z zakresu od 1 do 10 i znajdź jej odwrotność.

In [122]:
a = np.random.randint(1, 11, size=(3, 3))
a_inv = np.linalg.inv(a)
print("a =\n", a)
print("a_inv =\n", a_inv)

a =
 [[ 4  8 10]
 [ 2  4  1]
 [ 2  5  7]]
a_inv =
 [[ 1.4375 -0.375  -2.    ]
 [-0.75    0.5     1.    ]
 [ 0.125  -0.25   -0.    ]]


### 9. Utwórz macierz 4x4, wypełnij ją losowymi liczbami rzeczywistymi z zakresu od 0 do 1 i przetransponuj ją.

In [123]:
a = np.random.randint(1, 11, size=(4, 4))
print("a =\n", a)
print("a^T =\n", a.T)

a =
 [[ 8  8  5 10]
 [10  3  6 10]
 [ 4  2  6  1]
 [ 9  1  5  3]]
a^T =
 [[ 8 10  4  9]
 [ 8  3  2  1]
 [ 5  6  6  5]
 [10 10  1  3]]


### 10. Utwórz macierz o rozmiarze 3x4 i wektor o rozmiarze 4, wypełnij je losowymi liczbami całkowitymi z zakresu od 1 do 10 i pomnóż macierz przez wektor.

In [124]:
a = np.random.randint(1, 11, size=(3, 4))
b = np.random.randint(1, 11, size=4)
print("a =\n", a)
print("b =\n", b)
print("a • b =\n", np.dot(a, b))

a =
 [[ 8 10  9  9]
 [ 1  6  6 10]
 [ 1  7  2  3]]
b =
 [7 5 3 5]
a • b =
 [178 105  63]


### 11. Utwórz macierz o rozmiarze 2x3 i wektor o rozmiarze 3, wypełnij je losowymi liczbami rzeczywistymi z zakresu od 0 do 1 i pomnóż macierz przez wektor.

In [125]:
a = np.random.random((2, 3))
b = np.random.random(3)
print("a =\n", a)
print("b =\n", b)
print("a • b =\n", np.dot(a, b))

a =
 [[0.39952403 0.95737197 0.27551665]
 [0.33625177 0.31863141 0.14903921]]
b =
 [0.40058941 0.40354985 0.72761142]
a • b =
 [0.74686147 0.37172518]


### 12. Utwórz dwie macierze o rozmiarze 2x2, wypełnij je losowymi liczbami całkowitymi z zakresu od 1 do 10 i wykonaj ich mnożenie pierwiastkowe.

In [126]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
print("a =\n", a)
print("b =\n", b)
print("a * b =\n", a*b)

a =
 [[8 1]
 [6 7]]
b =
 [[ 4  5]
 [10 10]]
a * b =
 [[32  5]
 [60 70]]


### 13. Utwórz dwie macierze o rozmiarze 2x2, wypełnij je losowymi liczbami całkowitymi z zakresu od 1 do 10 i znajdź ich iloczyn.

In [127]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
print("a =\n", a)
print("b =\n", b)
print("a • b =\n", np.dot(a, b))

a =
 [[10 10]
 [ 8  9]]
b =
 [[1 4]
 [1 5]]
a • b =
 [[20 90]
 [17 77]]


### 14. Utwórz macierz 5x5, wypełnij ją losowymi liczbami całkowitymi z zakresu od 1 do 100 i znajdź sumę elementów macierzy.

In [128]:
a = np.random.randint(1, 101, size=(5, 5))
print("a =\n", a)
print("The sum of the matrix elements:", a.sum())

a =
 [[ 11  50  74  59   6]
 [ 25  97  69   1  18]
 [ 44  55   9  46  48]
 [ 84  99  62  19   8]
 [ 49  25  86 100  72]]
The sum of the matrix elements: 1216


### 15. Utwórz dwie macierze o rozmiarze 4x4, wypełnij je losowymi liczbami całkowitymi z zakresu od 1 do 10 i znajdź ich różnicę.

In [129]:
a = np.random.randint(1, 11, size=(4, 4))
b = np.random.randint(1, 11, size=(4, 4))
print("a =\n", a)
print("b =\n", b)
print("a - b =\n", a-b)

a =
 [[ 6  2  6  3]
 [ 7  8  2  1]
 [ 9 10  4  6]
 [ 1  8  7  7]]
b =
 [[ 4  3  6  9]
 [10  8  7  2]
 [ 1  4  1  1]
 [ 7  8  5  3]]
a - b =
 [[ 2 -1  0 -6]
 [-3  0 -5 -1]
 [ 8  6  3  5]
 [-6  0  2  4]]


### 16. Utwórz macierz 3x3, wypełnij ją losowymi liczbami rzeczywistymi z zakresu od 0 do 1 i znajdź wektor kolumnowy zawierający sumę elementów każdego wiersza macierzy.

In [130]:
a = np.random.random((3, 3))
print("a =\n", a)
b = a[:, 0] + a[:, 1] + a[:, 2]
print("A column vector containing the sum of the elements of each row of the matrix: \n", b)
print("The dimension of this vector is:", b.shape)

a =
 [[0.79068079 0.52810684 0.20694718]
 [0.72613422 0.10274709 0.40607371]
 [0.23152195 0.28996672 0.31449845]]
A column vector containing the sum of the elements of each row of the matrix: 
 [1.52573482 1.23495502 0.83598712]
The dimension of this vector is: (3,)


### 17. Utwórz macierz o rozmiarze 3x4 z dowolnymi liczbami całkowitymi i utwórz macierz z kwadratami tych liczb.

In [131]:
a = np.random.randint(100, size=(3, 4))
print("a =\n", a)
print("A matrix with the squares of these numbers: \n", np.power(a, 2))

a =
 [[99  9  5 44]
 [73  0 50 40]
 [71 16 72 35]]
A matrix with the squares of these numbers: 
 [[9801   81   25 1936]
 [5329    0 2500 1600]
 [5041  256 5184 1225]]


### 18. Utwórz wektor o rozmiarze 4, wypełnij go losowymi liczbami całkowitymi z zakresu od 1 do 50 i znajdź wektor pierwiastków kwadratowych z tych liczb.

In [132]:
a = np.random.randint(1, 51, size=4)
print("a =", a)
print("The vector of square roots of these numbers: \n", np.sqrt(a))

a = [45 33  1 11]
The vector of square roots of these numbers: 
 [6.70820393 5.74456265 1.         3.31662479]
